#!/usr/bin/env node

var request = require("request");
var jsdom = require("jsdom");
var _ = require("lodash-node");


var url = 'http://tool.ccb.com/outlet/frontOprNodeQuery.gsp';

var processing_provinces = function(provinces) {
    _.each(provinces, function(province) {
        processing_province(province);
    })
};

var body = function() {

};
var processing_province = function(province) {
    processing_page(1);
};

var processing_page = function(province, pageNo) {
    var parameters = '_NodeType=101&pageNo=' + pageNo
        + '&_Lev1Code=' + province.code + '&_Lev2Code=&_KeyWork=';

    request.post({
        url: url,
        body: parameters
    }, function (error, response, body) {
        if (error && response.statusCode != 200) {
            console.log('Get Url errors, Parameters: ', parameters);
            return;
        }
        var lastPage = true;
        jsdom.env(
            body,
            ["./jquery.js"],
            function (errors, window) {
                var $ = window.jQuery;
                $("#cen tbody tr").not(':first').each(function(index, tr) {
                    $(tr).find('td').each(function(index, td) {
                        if (index == 1) {
                            // console.log($(td).contents(':not(span)').text());
                            console.log(index, $(td).text());
                        } else {
                            console.log(index, $(td).text());
                        }
                    });
                });

                $("form[name='oprForm'] ul li:first a").each(function(index, ele) {
                    if ( $(ele).text() == '下一页' ) {
                        lastPage = false;
                        console.log('not last page!')
                    };
                });
            }
        );
        if (!lastPage) {
            next_page = pageNo + 1;
            processing_page(province, next_page);
        }
    });
 };


request({uri: url}, function(error, response, body) {
    jsdom.env(
        body,
        ["http://code.jquery.com/jquery.js"],
        function (errors, window) {
            if (errors) {
                console.log('Error: ', errors);
                return -1;
            }
            var $ = window.jQuery;
            var provinces = [];
            $('#province option').each(
                function(i, option) {
                    var obj = {};
                    obj.code = $(option).val();
                    obj.name = $(option).text();
                    provinces.push(obj);
                }
            );
            processing_provinces(provinces);
        }
    );
});